# Workflow to associate labels automatically
name: labeler
# Trigger the workflow on pull request events
on: [pull_request]
jobs:
  label:
    runs-on: [ ds-small ]
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.DS_ACTIONS_APP_PEM }}
          APP_ID: ${{ secrets.DS_ACTIONS_APP_ID }}
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        with:
          APP_PEM: ${{ secrets.DS_ACTIONS_APP_PEM }}
          APP_ID: ${{ secrets.DS_ACTIONS_APP_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_ACCESS_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/label-pr.yml
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TEST_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
